brew 'antigen'
brew 'asdf'
brew 'direnv'
brew 'git'
brew 'hub'
brew 'lsd'
brew 'mas'
brew 'pnpm'
brew 'trash'
brew 'tree'
brew 'zsh'
brew 'zsh-completions'

cask '1password'
cask 'adobe-creative-cloud'
cask 'autodesk-fusion'
cask 'cursor'
cask 'dropbox'
cask 'firefox'
cask 'ghostty'
cask 'github'
cask 'mos'
cask 'raycast'
cask 'sigmaos'
cask 'slack'
cask 'visual-studio-code'

# Gaming
cask 'battle-net'
cask 'curseforge'
cask 'discord'
cask 'steam'

mas 'Affinity Designer', id: 824_171_161
