brew 'antigen'
brew 'asdf'
brew 'direnv'
brew 'git'
brew 'hub'
brew 'mas'
brew 'terminal-notifier'
brew 'trash'
brew 'tree'
brew 'zsh'
brew 'zsh-completions'

cask '1password'
cask 'firefox'
cask 'github'
cask 'mos'
cask 'raycast'
cask 'slack'
cask 'visual-studio-code'

mas 'Affinity Designer', id: 824_171_161
