## Antigen

ZSHA_BASE=$HOME/.etc/antigen
source $ZSHA_BASE/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundles <<-BUNDLES
	brew
	bundler
	git
	heroku
	rails
	ruby
	ssh-agent
	tmux
	zsh-users/zsh-completions
	zsh-users/zsh-syntax-highlighting
	zsh-users/zsh-history-substring-search
	arialdomartini/oh-my-git
BUNDLES

if [ "$OSTYPE"="darwin11.0" ]; then
  antigen-bundle osx
fi

antigen theme arialdomartini/oh-my-git-themes arialdo-pathinline

antigen apply

## Editor

export EDITOR='subl -w'
export VISUAL='subl'

## Path

PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

export PATH="/usr/local/share/npm/bin:$PATH"

export PATH=$PATH:/opt/local/bin
export MANPATH=$MANPATH:/opt/local/share/man
export INFOPATH=$INFOPATH:/opt/local/share/info

## Ext

if [ -f ~/.aliases ]; then
	. ~/.aliases
fi

if [ -f ~/.private ]; then
  . ~/.private
fi

# brew install zsh-completions
fpath=(/usr/local/share/zsh-completions $fpath)

## Lang

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export ARCHFLAGS="-arch x86_64"

## Ruby

export RBENV_ROOT=/usr/local/var/rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

export RUBYMOTION_ANDROID_SDK=~/Dev/Ext/android-sdk-macosx
export RUBYMOTION_ANDROID_NDK=~/Dev/Ext/android-ndk-r10c

## GO

export GOPATH=$HOME/.go
export PATH=$PATH:/usr/local/opt/go/libexec/bin:${GOPATH//://bin:}/bin

## Misc

export HOMEBREW_CASK_OPTS="--caskroom=/usr/local/Caskroom"

source `brew --prefix`/etc/profile.d/z.sh

eval "$(direnv hook $0)"
